nrf52840:
  target: nrf52840
  compilers:
    - gcc
    - iar
  required_libs:
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-nrf52840-sdk
    - libopenthread-nrf52840-sdk-usb
    - libopenthread-nrf52840-sdk-spi
    - libopenthread-nrf52840-softdevice-sdk
    - libopenthread-nrf52840-softdevice-sdk-usb
    - libopenthread-nrf52840-softdevice-sdk-spi
    - libopenthread-platform-utils
    - libnordicsemi-nrf52840-radio-driver
    - libnordicsemi-nrf52840-radio-driver-softdevice
    - libopenthread-radio
    - libopenthread-rcp
    - libopenthread-rcp-spi
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52840-sdk
    - libopenthread-nrf52840
    - libmbedcrypto

keil:
  target: nrf52840
  compilers:
    - keil
  required_libs:
    - libmbedcrypto
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-nrf52840-sdk
    - libopenthread-nrf52840-sdk-usb
    - libopenthread-nrf52840-sdk-spi
    - libopenthread-nrf52840-softdevice-sdk
    - libopenthread-nrf52840-softdevice-sdk-usb
    - libopenthread-nrf52840-softdevice-sdk-spi
    - libopenthread-platform-utils
    - libnordicsemi-nrf52840-radio-driver
    - libnordicsemi-nrf52840-radio-driver-softdevice
    - libopenthread-radio
    - libopenthread-rcp
    - libopenthread-rcp-spi
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52840-sdk
    - libopenthread-nrf52840

nrf52811:
  target: nrf52811
  compilers:
    - gcc
    - iar
    - keil
  required_libs:
    - libmbedcrypto
    - libopenthread-mtd
    - libopenthread-nrf52811-sdk
    - libopenthread-nrf52811-sdk-spi
    - libopenthread-platform-utils
    - libopenthread-radio
    - libopenthread-cli-mtd
    - libopenthread-rcp
    - libopenthread-rcp-spi
    - libnordicsemi-nrf52811-radio-driver
  dropped_libs:
    - libjlinkrtt
    - libopenthread-ftd
    - libopenthread-cli-ftd
    - libnordicsemi-nrf52811-sdk
    - libopenthread-nrf52811
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-nrf52811-sdk-usb
    - libopenthread-nrf52811-softdevice-sdk
    - libopenthread-nrf52811-softdevice-sdk-usb
    - libopenthread-nrf52811-softdevice-sdk-spi
    - libnordicsemi-nrf52811-radio-driver-softdevice

nrf52833:
  target: nrf52833
  compilers:
    - gcc
    - keil
    - iar
  required_libs:
    - libmbedcrypto
    - libopenthread-cli-ftd
    - libopenthread-cli-mtd
    - libopenthread-ftd
    - libopenthread-mtd
    - libopenthread-ncp-ftd
    - libopenthread-ncp-ftd-spi
    - libopenthread-ncp-mtd
    - libopenthread-ncp-mtd-spi
    - libopenthread-nrf52833-sdk
    - libopenthread-nrf52833-sdk-usb
    - libopenthread-nrf52833-sdk-spi
    - libopenthread-nrf52833-softdevice-sdk
    - libopenthread-nrf52833-softdevice-sdk-usb
    - libopenthread-nrf52833-softdevice-sdk-spi
    - libopenthread-platform-utils
    - libnordicsemi-nrf52833-radio-driver
    - libnordicsemi-nrf52833-radio-driver-softdevice
    - libopenthread-radio
    - libopenthread-rcp
    - libopenthread-rcp-spi
  dropped_libs:
    - libjlinkrtt
    - libnordicsemi-nrf52833-sdk
    - libopenthread-nrf52833
